name: npm publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    strategy:
        matrix: 
            version: [14, 16, 20]
            os: [ubuntu-latest, windows-latest]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
